import Head from 'next/head'
import Layout from '@/components/Layout'
import Form from '@/components/Form'
import styles from '@/styles/pages/Home.module.scss'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.wrapper}>
          <div className={styles.container_title}>
            <h1>
              Renseignez vos données afin d'obtenir votre empreinte carbone !
            </h1>
          </div>
          <Form />
        </div>
      </main>
    </Layout>
  )
}
